
import pandas as pd
import lightgbm as lgb
import mlflow
import logging
from pathlib import Path
from sklearn.model_selection import train_test_split
import sys

# Add project root
sys.path.append(str(Path(__file__).resolve().parent.parent.parent.parent))
from medins_ml_utils.utils import load_config, setup_directories

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def main():
    config = load_config('config.json')
    paths = setup_directories(config)
    mlflow.set_tracking_uri("file:./mlruns")
    mlflow.set_experiment("FWA_Detection_v1")
    
    logging.info("--- FWA Stage 2: Supervised Model Retraining (Active Learning Loop) ---")
    
    # Load the worklist generated by the unsupervised model
    worklist_path = Path(paths['output_dir']) / "fwa_worklist.csv"
    if not worklist_path.exists():
        logging.error(f"Worklist not found at {worklist_path}. Run Stage 1 first.")
        return
        
    # Labeled data is small (worklist), so Pandas is fine here.
    labeled_data = pd.read_csv(worklist_path)
    
    # Simulate human labeling
    if len(labeled_data) < 5:
        logging.warning("Not enough data to train supervised model.")
        return

    anomaly_threshold = labeled_data['anomaly_score'].quantile(0.25)
    labeled_data['is_fraud'] = (labeled_data['anomaly_score'] < anomaly_threshold).astype(int)
    logging.info(f"Simulated labeling: Found {labeled_data['is_fraud'].sum()} fraud cases from the worklist.")
    
    if labeled_data['is_fraud'].sum() < 2 or (len(labeled_data) - labeled_data['is_fraud'].sum()) < 2:
        logging.warning("Classes not balanced enough for Stratified Split/Training. Skipping supervised train.")
        return

    features = [col for col in labeled_data.columns if col not in ['provider_license_key', 'is_fraud', 'anomaly_score']]
    X = labeled_data[features]
    y = labeled_data['is_fraud']
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    
    Path(paths['data_output_dir']).mkdir(exist_ok=True, parents=True)
    X_test.to_csv(Path(paths['data_output_dir']) / 'X_test_fwa.csv', index=False)
    y_test.to_csv(Path(paths['data_output_dir']) / 'y_test_fwa.csv', index=False)

    with mlflow.start_run(run_name="FWA Supervised Training") as run:
        params = config.get('supervised_model_params', {})
        mlflow.log_params(params)
        mlflow.log_metric("labeled_sample_size", len(labeled_data))
        
        model = lgb.LGBMClassifier(**params)
        model.fit(X_train, y_train)
        
        mlflow.sklearn.log_model(
            sk_model=model,
            artifact_path="fwa-model",
            registered_model_name="fwa-detection-model",
            input_example=X_train.head(1)
        )
    logging.info("Supervised FWA model trained and registered to MLflow as 'fwa-detection-model'")

if __name__ == "__main__":
    main()
